'use strict';

const STORAGE='fala-music-state-v6';
const LEGACY_KEYS=['fala-music-state-v5','fala-music-state-v4','fala-music-state-v3','fala-music-state-v2','fala-music-state-v1'];
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const initials=s=>String(s||'FM').split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));

const SEED_TRACKS=[
{id:'enter-czwarta',title:'Czwarta Pixa',artist:'Enter',provider:'youtube',url:'https://www.youtube.com/watch?v=hFUmQ_eiF_Q',cover:'https://i.ytimg.com/vi/hFUmQ_eiF_Q/hqdefault.jpg',tags:['vixa','polska','party'],seed:true},
{id:'gang-krolowie',title:'Królowie życia',artist:'Gang Albanii',provider:'youtube',url:'https://www.youtube.com/watch?v=pZr3K7F9fqQ',cover:'https://i.ytimg.com/vi/pZr3K7F9fqQ/hqdefault.jpg',tags:['polska','party'],seed:true},
{id:'gang-klub',title:'Klub Go Go',artist:'Gang Albanii',provider:'youtube',url:'https://www.youtube.com/watch?v=pZr3K7F9fqQ&t=586s',cover:'https://i.ytimg.com/vi/pZr3K7F9fqQ/hqdefault.jpg',tags:['polska','party'],seed:true},
{id:'gang-dubaj',title:'Jedziemy do Dubaju',artist:'Gang Albanii',provider:'youtube',url:'https://www.youtube.com/watch?v=pZr3K7F9fqQ&t=2278s',cover:'https://i.ytimg.com/vi/pZr3K7F9fqQ/hqdefault.jpg',tags:['polska','party'],seed:true},
{id:'sentino-casablanca',title:'CASABLANCA',artist:'Sentino, BNP',provider:'youtube',url:'https://www.youtube.com/watch?v=B0B_mQZfeiY',cover:'https://i.ytimg.com/vi/B0B_mQZfeiY/hqdefault.jpg',tags:['polska','rap','lato'],seed:true},
{id:'malik-belly',title:'Belly Dance',artist:'Malik Montana',provider:'youtube',url:'https://www.youtube.com/watch?v=D73aEjo_l-Y',cover:'https://i.ytimg.com/vi/D73aEjo_l-Y/hqdefault.jpg',tags:['polska','trap'],seed:true},
{id:'kizo-lato',title:'Nasze lato',artist:'Kizo, Wac Toja',provider:'youtube',url:'https://www.youtube.com/watch?v=pDg6mV79AC4',cover:'https://i.ytimg.com/vi/pDg6mV79AC4/hqdefault.jpg',tags:['polska','rap','lato'],seed:true},
{id:'white-morgan',title:'Morgan',artist:'White 2115',provider:'spotify',url:'https://open.spotify.com/track/6OE7voRcEvrBPDl7wqjn4D',cover:'',tags:['polska','rap','lato'],seed:true},
{id:'duran-hungry',title:'Hungry Like the Wolf',artist:'Duran Duran',provider:'youtube',url:'https://www.youtube.com/watch?v=oJL-lCzEXgI',cover:'https://i.ytimg.com/vi/oJL-lCzEXgI/hqdefault.jpg',tags:['80s','classic'],seed:true},
{id:'berlin-breath',title:'Take My Breath Away',artist:'Berlin',provider:'youtube',url:'https://www.youtube.com/watch?v=Bx51eegLTY8',cover:'https://i.ytimg.com/vi/Bx51eegLTY8/hqdefault.jpg',tags:['80s','classic'],seed:true},
{id:'massive-teardrop',title:'Teardrop',artist:'Massive Attack',provider:'youtube',url:'https://www.youtube.com/watch?v=u7K72X4eo_s',cover:'https://i.ytimg.com/vi/u7K72X4eo_s/hqdefault.jpg',tags:['classic','trip hop'],seed:true},
{id:'abba-money',title:'Money, Money, Money',artist:'ABBA',provider:'youtube',url:'https://www.youtube.com/watch?v=ETxmCCsMoD0',cover:'https://i.ytimg.com/vi/ETxmCCsMoD0/hqdefault.jpg',tags:['classic','pop'],seed:true}
];

const SEED_PLAYLISTS=[
{id:'my-wave',name:'Moja Fala',description:'Twoja osobista mieszanka ze wszystkich źródeł.',accent:'#ff5a2c',trackIds:[],custom:false},
{id:'polska-start',name:'Polska Start',description:'Rap, vixa, lato i polska energia.',accent:'#dc2f3f',trackIds:['enter-czwarta','gang-krolowie','sentino-casablanca','malik-belly','kizo-lato','white-morgan'],custom:false},
{id:'vixa-party',name:'Vixa & Party',description:'Szybka imprezowa fala.',accent:'#8c5cff',trackIds:['enter-czwarta','gang-krolowie','gang-klub','gang-dubaj','kizo-lato'],custom:false},
{id:'worldwide',name:'Worldwide Classics',description:'Klasyki spoza polskiej fali.',accent:'#2e9cff',trackIds:['duran-hungry','berlin-breath','massive-teardrop','abba-money'],custom:false}
];

const ARTISTS={
'Enter':['Vixa starter','#ff9b2f','#6f153a'],'Gang Albanii':['Polskie klasyki imprezowe','#c82b2b','#130b0e'],'Sentino':['Lato i uliczny rap','#27a9aa','#132743'],'Malik Montana':['Polski trap','#7850ff','#1c1335'],'White 2115':['Melodyjny rap','#4e8cff','#111d42'],'Kizo':['Imprezowe lato','#ffad2e','#6a2447'],'Duran Duran':['Międzynarodowe lata 80.','#e55a8d','#2b1747']};

function clone(x){return JSON.parse(JSON.stringify(x))}
function normalizeState(raw){
 const base=raw&&typeof raw==='object'?raw:{};
 const tracks=Array.isArray(base.tracks)?base.tracks.filter(Boolean):clone(SEED_TRACKS);
 for(const seed of SEED_TRACKS)if(!tracks.some(t=>t.id===seed.id||t.url===seed.url))tracks.push(clone(seed));
 let playlists=Array.isArray(base.playlists)?base.playlists.filter(Boolean):clone(SEED_PLAYLISTS);
 for(const seed of SEED_PLAYLISTS)if(!playlists.some(p=>p.id===seed.id))playlists.push(clone(seed));
 playlists=playlists.filter(p=>p.id!=='liked-songs').map((p,i)=>({id:p.id||uid('playlist'),name:p.name||`Playlista ${i+1}`,description:p.description||'',accent:p.accent||['#ff5a2c','#dc2f3f','#8c5cff','#21c77a','#2e9cff'][i%5],custom:p.custom??!SEED_PLAYLISTS.some(s=>s.id===p.id),trackIds:[...new Set(Array.isArray(p.trackIds)?p.trackIds:[])]}));
 return{tracks,playlists,likedIds:[...new Set(base.likedIds||[])],recentIds:[...new Set(base.recentIds||[])],settings:{volume:.78,lastVolume:.78,googleClientId:'',shuffle:false,repeat:false,...(base.settings||{})}};
}
function loadState(){
 try{const saved=JSON.parse(localStorage.getItem(STORAGE)||'null');if(saved)return normalizeState(saved)}catch{}
 for(const key of LEGACY_KEYS){try{const old=JSON.parse(localStorage.getItem(key)||'null');if(old)return normalizeState(old)}catch{}}
 return normalizeState(null);
}
let state=loadState();
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{}renderSidebar();updateCounts()}

let currentView='home',currentPlaylist=null,currentTrack=null,currentQueue=[],queueIndex=-1,activeProvider='youtube',searchTimer=null,searchNonce=0,pickerTrackId=null,drawerTab='player',lyricsCache=new Map(),lyricsData=null,lyricsActive=-1,tokenClient=null,youtubeToken='',youtubeProfile=null,ytPlayer=null,ytReadyPromise=null,scWidget=null,playbackMode='idle',playbackDuration=0,playbackPosition=0,ticker=null,selectedPlaylistColor='#ff5a2c';

function providerLabel(p){return({youtube:'YouTube',soundcloud:'SoundCloud',spotify:'Spotify',preview:'Podgląd',local:'Lokalny'})[p]||'Źródło'}
function providerColor(p){return({youtube:'#ff4545',soundcloud:'#ff7a21',spotify:'#1ed760',preview:'#ffbd45'})[p]||'#ffbd45'}
function mediaType(t){if(t.preview||t.previewUrl)return{label:`PODGLĄD${t.duration?` · ${formatTime(t.duration)}`:''}`,cls:''};if(t.provider==='youtube'||t.provider==='soundcloud')return{label:'PEŁNY UTWÓR',cls:'full'};return{label:'BRAK PODGLĄDU',cls:'muted'}}
function youtubeId(url=''){try{const u=new URL(url);if(u.hostname.includes('youtu.be'))return u.pathname.slice(1);if(u.hostname.includes('youtube.com'))return u.searchParams.get('v')||u.pathname.split('/').filter(Boolean).pop()}catch{}return''}
function soundcloudUrl(t){return t.provider==='soundcloud'?t.url:''}
function validUrl(s){try{return/^https?:$/.test(new URL(s).protocol)}catch{return false}}
function formatTime(sec){if(!Number.isFinite(sec)||sec<0)return'0:00';const m=Math.floor(sec/60),s=Math.floor(sec%60);return`${m}:${String(s).padStart(2,'0')}`}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2200)}
function setCover(el,t){el.style.backgroundImage=t?.cover?`url("${String(t.cover).replace(/"/g,'%22')}")`:'';if(!t?.cover)el.style.background='linear-gradient(135deg,#ff9630,#651d48)'}
function artwork(t,cls='row-cover'){const bg=t.cover?`style="background-image:url('${esc(t.cover).replace(/'/g,'%27')}')"`:'';return`<button class="${cls}" ${bg} data-play-track="${esc(t.id)}" title="Odtwórz ${esc(t.title)}"><span class="cover-play">▶</span>${t.cover?'':`<b>${esc(initials(t.artist))}</b>`}</button>`}
function getTrack(id){return state.tracks.find(t=>t.id===id)}
function playlistTracks(p){return(p?.trackIds||[]).map(getTrack).filter(Boolean)}

function renderSidebar(){
 const nav=$('#playlist-nav');if(!nav)return;
 const items=[{id:'liked-songs',name:'Polubione',accent:'#dc2f3f',trackIds:state.likedIds},...state.playlists];
 nav.innerHTML=items.map(p=>`<button data-playlist="${esc(p.id)}" class="${currentPlaylist===p.id?'active':''}"><i style="--pc:${esc(p.accent||'#ff5a2c')}"></i><b>${esc(p.name)}</b><small>${p.trackIds.length}</small></button>`).join('');
}
function updateCounts(){$('#library-count').textContent=state.tracks.length;$('#liked-count').textContent=state.likedIds.length}
function setView(view,arg=null){
 currentView=view;currentPlaylist=view==='playlist'?arg:null;
 $$('.main-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));renderSidebar();
 if(view==='home')renderHome();else if(view==='search')renderSearch($('#global-search').value);else if(view==='library')renderLibrary();else if(view==='liked')renderLiked();else if(view==='playlist')renderPlaylist(arg);else if(view==='artist')renderArtist(arg);
}

function renderHome(){
 const recent=state.recentIds.map(getTrack).filter(Boolean).slice(0,8);const starter=recent.length?recent:playlistTracks(state.playlists.find(p=>p.id==='polska-start'));
 const cards=[{id:'liked-songs',name:'Polubione',description:'Każde serce trafia tutaj automatycznie.',accent:'#dc2f3f',trackIds:state.likedIds},...state.playlists];
 $('#view').innerHTML=`<section class="hero"><div class="hero-copy"><span class="hero-ribbon">POLSKA FALA · GLOBAL SOUND</span><h1>Polska energia.<br><span>Cały świat.</span></h1><p>Twoja dopracowana biblioteka polskiego rapu, vixy, klasyków i wszystkiego pomiędzy. YouTube może działać z Twoim kontem, a SoundCloud bez logowania.</p><div class="hero-actions"><button class="primary-button" data-view="search">⌕ Znajdź muzykę</button><button class="secondary-button" data-play-playlist="polska-start">▶ Uruchom Polską Falę</button><button class="secondary-button" data-open-create>＋ Nowa playlista</button></div><div class="hero-stats"><div class="hero-stat"><strong>${state.tracks.length}</strong><span>utworów</span></div><div class="hero-stat"><strong>${state.playlists.length+1}</strong><span>playlist</span></div><div class="hero-stat"><strong>${state.likedIds.length}</strong><span>polubionych</span></div></div></div><div class="polish-disc"></div></section>
 <section class="section"><div class="section-head"><div><h2>Twoje fale</h2><p>Własne playlisty, kolekcje i automatyczne polubienia.</p></div><button class="secondary-button" data-open-create>＋ Utwórz playlistę</button></div><div class="playlist-grid">${cards.map(p=>playlistCard(p)).join('')}<button class="playlist-card" style="--pc:#ff5a2c" data-open-create><strong>＋ Zbuduj nową falę</strong><p>Nazwij ją, wybierz kolor i dodawaj utwory bez wielkiego okna.</p><small>Twoja kolekcja</small></button></div></section>
 <section class="section"><div class="section-head"><div><h2>Artyści startowi</h2><p>Polska przede wszystkim, ale bez zamykania się na świat.</p></div></div><div class="card-grid">${Object.entries(ARTISTS).map(([name,[sub,a1,a2]])=>`<button class="artist-card" style="--pc:${a1}" data-artist="${esc(name)}"><div class="artist-avatar" style="--a1:${a1};--a2:${a2}">${esc(initials(name))}</div><h3>${esc(name)}</h3><p>${esc(sub)}</p></button>`).join('')}</div></section>
 <section class="section"><div class="section-head"><div><h2>${recent.length?'Ostatnio odtwarzane':'Polska Start'}</h2><p>${recent.length?'Wróć do swojej kolejki.':'Startowa kolekcja polskiej muzyki.'}</p></div></div>${trackTable(starter)}</section>`;
}
function playlistCard(p){return`<button class="playlist-card" style="--pc:${esc(p.accent||'#ff5a2c')}" data-playlist="${esc(p.id)}"><span class="eyebrow">${p.id==='liked-songs'?'AUTO PLAYLIST':p.custom?'TWOJA PLAYLISTA':'FALA COLLECTION'}</span><strong>${esc(p.name)}</strong><p>${esc(p.description||'Twoja zapisana muzyka.')}</p><small>${p.trackIds.length} utworów</small></button>`}
function renderLibrary(){const tracks=[...state.tracks].sort((a,b)=>(b.addedAt||0)-(a.addedAt||0));$('#view').innerHTML=`<span class="eyebrow">TWOJA KOLEKCJA</span><h1 class="page-title">Biblioteka</h1><p class="subtitle">Wszystkie zapisane utwory z YouTube, SoundCloud i podglądów.</p><section class="section">${trackTable(tracks,'Biblioteka jest pusta','Znajdź muzykę i dodaj ją do Fali.')}</section>`}
function renderLiked(){const tracks=state.likedIds.map(getTrack).filter(Boolean);$('#view').innerHTML=`<section class="playlist-hero" style="--pc:#dc2f3f"><div class="playlist-cover-large">♥</div><div><span class="eyebrow">AUTOMATYCZNA PLAYLISTA</span><h1>Polubione</h1><p class="playlist-description">Każdy utwór oznaczony sercem pojawia się tutaj od razu.</p>${tracks.length?'<button class="primary-button" data-play-liked>▶ Odtwórz wszystko</button>':''}</div></section><section class="section">${trackTable(tracks,'Brak polubionych','Kliknij ♡ przy dowolnym utworze.')}</section>`}
function renderPlaylist(id){
 if(id==='liked-songs')return renderLiked();const p=state.playlists.find(x=>x.id===id);if(!p)return setView('home');const tracks=playlistTracks(p);
 $('#view').innerHTML=`<section class="playlist-hero" style="--pc:${esc(p.accent)}"><div class="playlist-cover-large">${esc(initials(p.name))}</div><div><span class="eyebrow">${p.custom?'TWOJA PLAYLISTA':'FALA COLLECTION'}</span><h1>${esc(p.name)}</h1><p class="playlist-description">${esc(p.description||'Twoja osobista kolekcja.')}</p><div class="hero-actions"><button class="primary-button" data-play-playlist="${esc(p.id)}">▶ Odtwórz</button><button class="secondary-button" data-view="search">＋ Dodaj muzykę</button>${p.custom?`<button class="secondary-button" data-delete-playlist="${esc(p.id)}">Usuń playlistę</button>`:''}</div></div></section><section class="section">${trackTable(tracks,'Ta playlista jest pusta','Wyszukaj utwór i kliknij +.')}</section>`;
}
function renderArtist(name){const tracks=state.tracks.filter(t=>t.artist.toLowerCase().includes(name.toLowerCase()));$('#view').innerHTML=`<span class="eyebrow">ARTYSTA</span><h1 class="page-title">${esc(name)}</h1><p class="subtitle">${tracks.length} utworów w Twojej bibliotece.</p><section class="section">${trackTable(tracks,'Brak utworów','Wyszukaj artystę i dodaj utwory.')}</section>`}
function trackTable(tracks,emptyTitle='Brak utworów',emptyText='Dodaj muzykę, aby zacząć.'){
 if(!tracks.length)return`<div class="empty-state"><h3>${esc(emptyTitle)}</h3><p>${esc(emptyText)}</p><button class="primary-button" data-view="search">Szukaj muzyki</button></div>`;
 return`<div class="track-list">${tracks.map((t,i)=>{const liked=state.likedIds.includes(t.id),meta=mediaType(t),pl=state.playlists.find(p=>p.trackIds.includes(t.id));return`<div class="track-row" data-track-id="${esc(t.id)}" style="animation-delay:${Math.min(i*22,250)}ms"><div class="track-number">${i+1}</div><div class="track-main">${artwork(t)}<div class="track-copy"><strong>${esc(t.title)}</strong><span>${esc(t.artist)}</span><div class="track-meta"><span class="media-badge ${meta.cls}">${meta.label}</span></div></div></div><div class="playlist-name provider-label">${esc(liked?'Polubione':pl?.name||'—')}</div><div class="provider-label">${esc(providerLabel(t.provider))}</div><div class="row-actions"><button class="icon-button" data-like-track="${esc(t.id)}" title="${liked?'Usuń z polubionych':'Polub'}">${liked?'♥':'♡'}</button><button class="icon-button" data-add-track="${esc(t.id)}" title="Dodaj do playlist">＋</button><button class="icon-button" data-play-track="${esc(t.id)}" title="Odtwórz">▶</button>${t.seed?'':`<button class="icon-button" data-delete-track="${esc(t.id)}" title="Usuń">×</button>`}</div></div>`}).join('')}</div>`;
}

function renderSearch(query=''){
 const q=(query||'').trim();const target=currentPlaylist&&currentPlaylist!=='liked-songs'?currentPlaylist:(state.playlists.find(p=>p.id==='my-wave')?.id||state.playlists[0]?.id||'');
 $('#view').innerHTML=`<span class="eyebrow">ODKRYWAJ</span><h1 class="page-title">Szukaj każdej fali</h1><p class="subtitle">YouTube z kontem, SoundCloud bez konta i legalne podglądy muzyczne.</p><div class="provider-tabs">${['youtube','soundcloud','preview'].map(p=>`<button class="provider-tab ${activeProvider===p?'active':''}" style="--provider-color:${providerColor(p)}" data-provider-tab="${p}">${providerLabel(p)}</button>`).join('')}</div><div class="search-workspace"><div class="search-row"><input id="provider-query" value="${esc(q)}" placeholder="${activeProvider==='soundcloud'?'Wklej link SoundCloud albo wpisz nazwę':'Wpisz artystę lub utwór'}"><select id="search-playlist">${state.playlists.map(p=>`<option value="${esc(p.id)}" ${p.id===target?'selected':''}>Dodaj do: ${esc(p.name)}</option>`).join('')}<option value="liked-songs">Dodaj do: Polubione</option></select><button class="primary-button" id="run-search">Szukaj</button></div><p class="search-note">${searchHelp()}</p><div id="search-results" class="section"></div></div>`;
 runSearch(q);
}
function searchHelp(){if(activeProvider==='youtube')return youtubeToken?'Wyniki pochodzą z prawdziwego YouTube. Dodanie zapisuje utwór w Fali; opcjonalnie możesz także dodać film do playlisty YouTube.':'Połącz YouTube w ustawieniach, aby uzyskać prawdziwe wyniki i playlisty konta. Bez konta Fala pokaże bibliotekę i legalne podglądy.';if(activeProvider==='soundcloud')return'Wklej publiczny link SoundCloud. Odtwarzanie używa oficjalnego widgetu i nie wymaga konta.';return'Podglądy pochodzą z publicznych metadanych i zwykle trwają około 30 sekund.'}
async function runSearch(q){
 const box=$('#search-results');if(!box)return;const query=(q||'').trim();if(query.length<2){box.innerHTML='<div class="empty-state"><h3>Zacznij pisać</h3><p>Spróbuj: Gibbs, White 2115, Gang Albanii albo Duran Duran.</p></div>';return}
 if(activeProvider==='soundcloud'&&validUrl(query)&&query.includes('soundcloud.com')){box.innerHTML=resultGrid([{id:'sc-temp',title:'Publiczny utwór SoundCloud',artist:'SoundCloud',provider:'soundcloud',url:query,cover:'',temporary:true}]);return}
 const local=state.tracks.filter(t=>`${t.title} ${t.artist} ${(t.tags||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase())).slice(0,20);
 box.innerHTML=`${local.length?`<div class="section-head"><div><h2>Twoja biblioteka</h2><p>${local.length} dopasowań</p></div></div>${resultGrid(local)}`:''}<div class="section-head" style="margin-top:25px"><div><h2>${activeProvider==='youtube'?'YouTube':'Podglądy'}</h2><p>Ładowanie wyników…</p></div></div><div class="spinner"></div>`;
 const nonce=++searchNonce;
 try{
  let items=[];
  if(activeProvider==='youtube'&&youtubeToken)items=await youtubeSearch(query);
  else items=await itunesSearch(query);
  if(nonce!==searchNonce||!$('#search-results'))return;
  box.innerHTML=`${local.length?`<div class="section-head"><div><h2>Twoja biblioteka</h2><p>${local.length} dopasowań</p></div></div>${resultGrid(local)}`:''}<div class="section-head" style="margin-top:25px"><div><h2>${activeProvider==='youtube'&&youtubeToken?'Prawdziwe wyniki YouTube':'Legalne podglądy'}</h2><p>${items.length} wyników</p></div></div>${resultGrid(items)}`;
 }catch(e){box.innerHTML+=`<div class="empty-state"><h3>Nie udało się pobrać wyników</h3><p>${esc(e.message||'Spróbuj ponownie.')}</p></div>`}
}
function resultGrid(items){if(!items.length)return'<div class="empty-state"><h3>Brak wyników</h3></div>';return`<div class="result-grid">${items.map((t,i)=>resultCard(t,i)).join('')}</div>`}
function resultCard(t,i){const meta=mediaType(t),payload=encodeURIComponent(JSON.stringify(t));const bg=t.cover?`style="background-image:url('${esc(t.cover).replace(/'/g,'%27')}')"`:'';return`<article class="result-card" style="animation-delay:${Math.min(i*35,280)}ms"><button class="result-cover" ${bg} data-preview-result="${payload}"><span class="cover-play">▶</span>${t.cover?'':esc(initials(t.artist))}</button><div class="result-copy"><strong>${esc(t.title)}</strong><span>${esc(t.artist)}</span><span class="media-badge ${meta.cls}">${meta.label}</span><div class="result-actions"><button class="small-button" data-preview-result="${payload}">▶ Odtwórz</button><button class="small-button accent" data-save-result="${payload}">＋ Dodaj</button>${t.provider==='youtube'&&youtubeToken?'<button class="small-button" data-save-youtube-result="'+payload+'">YouTube +</button>':''}</div></div></article>`}

function itunesSearch(term){return new Promise((resolve,reject)=>{const cb='falaItunes'+Date.now()+Math.random().toString(36).slice(2);const script=document.createElement('script');let done=false;const finish=(v,err=false)=>{if(done)return;done=true;delete window[cb];script.remove();clearTimeout(timer);err?reject(v):resolve(v)};window[cb]=data=>{const seen=new Set();const out=(data.results||[]).filter(x=>x.trackName&&x.artistName).filter(x=>{const k=(x.trackName+'|'+x.artistName).toLowerCase();if(seen.has(k))return false;seen.add(k);return true}).slice(0,25).map(x=>({id:uid('preview-result'),title:x.trackName,artist:x.artistName,cover:(x.artworkUrl100||'').replace('100x100','600x600'),preview:x.previewUrl||'',previewUrl:x.previewUrl||'',duration:Math.round((x.trackTimeMillis||0)/1000),provider:'preview',collection:x.collectionName||'',temporary:true}));finish(out)};script.onerror=()=>finish(new Error('Podglądy są chwilowo niedostępne.'),true);script.src=`https://itunes.apple.com/search?term=${encodeURIComponent(term)}&media=music&entity=song&limit=30&country=PL&callback=${cb}`;document.head.appendChild(script);const timer=setTimeout(()=>finish(new Error('Przekroczono czas wyszukiwania.'),true),9000)})}
async function youtubeSearch(q){
 const params=new URLSearchParams({part:'snippet',type:'video',videoEmbeddable:'true',maxResults:'25',q});const r=await fetch(`https://www.googleapis.com/youtube/v3/search?${params}`,{headers:{Authorization:`Bearer ${youtubeToken}`}});if(r.status===401){disconnectYoutube(false);throw new Error('Sesja YouTube wygasła. Połącz konto ponownie.')}if(!r.ok)throw new Error('YouTube nie zwrócił wyników. Sprawdź API w Google Cloud.');const data=await r.json();return(data.items||[]).map(x=>({id:`yt-${x.id.videoId}`,title:decodeHtml(x.snippet.title),artist:decodeHtml(x.snippet.channelTitle),provider:'youtube',url:`https://www.youtube.com/watch?v=${x.id.videoId}`,cover:x.snippet.thumbnails?.high?.url||x.snippet.thumbnails?.medium?.url||'',youtubeVideoId:x.id.videoId,temporary:true}))
}
function decodeHtml(s){const d=document.createElement('textarea');d.innerHTML=s;return d.value}

function selectedSearchPlaylist(){return $('#search-playlist')?.value||'my-wave'}
function saveResult(raw,openPicker=false){
 const data=typeof raw==='string'?JSON.parse(decodeURIComponent(raw)):raw;let t=state.tracks.find(x=>(data.url&&x.url===data.url)||(x.title===data.title&&x.artist===data.artist));
 if(!t){t={...data,id:uid(data.provider||'track'),temporary:false,addedAt:Date.now(),seed:false};state.tracks.unshift(t)}else Object.assign(t,{cover:t.cover||data.cover,preview:t.preview||data.preview,previewUrl:t.previewUrl||data.previewUrl,url:t.url||data.url});
 const target=selectedSearchPlaylist();addToPlaylist(t.id,target,false);save();toast(`Dodano do ${target==='liked-songs'?'Polubionych':state.playlists.find(p=>p.id===target)?.name||'Fali'}`);if(openPicker)openPlaylistPanel(t.id);renderSearch($('#provider-query')?.value||'');return t;
}
function addToPlaylist(trackId,playlistId,notify=true){if(playlistId==='liked-songs'){if(!state.likedIds.includes(trackId))state.likedIds.unshift(trackId);if(notify)toast('Dodano do Polubionych');return}const p=state.playlists.find(x=>x.id===playlistId);if(!p)return;if(!p.trackIds.includes(trackId))p.trackIds.unshift(trackId);if(notify)toast(`Dodano do ${p.name}`)}
function toggleLike(id){const i=state.likedIds.indexOf(id);if(i<0){state.likedIds.unshift(id);toast('Dodano do Polubionych')}else{state.likedIds.splice(i,1);toast('Usunięto z Polubionych')}save();updatePlayer();rerenderCurrent()}
function rerenderCurrent(){if(currentView==='playlist')renderPlaylist(currentPlaylist);else setView(currentView)}

function openPlaylistPanel(id,anchor=null){pickerTrackId=id;const t=getTrack(id);if(!t)return;const panel=$('#playlist-panel');$('#playlist-panel-title').textContent=`${t.title} — playlisty`;renderPlaylistOptions();panel.classList.add('open');panel.setAttribute('aria-hidden','false');if(anchor){const r=anchor.getBoundingClientRect();panel.style.left=`${clamp(r.left,14,innerWidth-panel.offsetWidth-14)}px`;panel.style.right='auto';panel.style.top=`${clamp(r.bottom+8,75,innerHeight-panel.offsetHeight-125)}px`;panel.style.bottom='auto'}else{panel.style.left='';panel.style.right='22px';panel.style.top='';panel.style.bottom='124px'}}
function renderPlaylistOptions(){const t=getTrack(pickerTrackId);if(!t)return;const rows=[{id:'liked-songs',name:'Polubione',description:'Automatyczne ulubione',accent:'#dc2f3f',checked:state.likedIds.includes(t.id)},...state.playlists.map(p=>({...p,checked:p.trackIds.includes(t.id)}))];$('#playlist-options').innerHTML=rows.map(p=>`<label class="playlist-option"><i style="--pc:${esc(p.accent)}"></i><span><strong>${esc(p.name)}</strong><small>${esc(p.description||'Twoja playlista')}</small></span><input type="checkbox" value="${esc(p.id)}" ${p.checked?'checked':''}></label>`).join('')}
function syncPickerChoices(){const t=getTrack(pickerTrackId);if(!t)return;const checked=new Set($$('#playlist-options input:checked').map(x=>x.value));if(checked.has('liked-songs')){if(!state.likedIds.includes(t.id))state.likedIds.unshift(t.id)}else state.likedIds=state.likedIds.filter(id=>id!==t.id);for(const p of state.playlists){if(checked.has(p.id)){if(!p.trackIds.includes(t.id))p.trackIds.unshift(t.id)}else p.trackIds=p.trackIds.filter(id=>id!==t.id)}save();toast('Playlisty zaktualizowane');rerenderCurrent()}
function closeMiniPanels(){$$('.mini-panel').forEach(p=>{p.classList.remove('open');p.setAttribute('aria-hidden','true')})}
function openCreatePanel(){closeMiniPanels();$('#create-panel').classList.add('open');$('#new-playlist-name').focus()}
function createPlaylist(){const name=$('#new-playlist-name').value.trim();if(!name)return toast('Wpisz nazwę playlisty');const p={id:uid('playlist'),name,description:$('#new-playlist-description').value.trim(),accent:selectedPlaylistColor,custom:true,trackIds:[]};state.playlists.push(p);save();$('#new-playlist-name').value='';$('#new-playlist-description').value='';closeMiniPanels();setView('playlist',p.id);toast('Playlista utworzona')}
function quickCreatePlaylist(){const input=$('#quick-playlist-name'),name=input.value.trim();if(!name)return toast('Wpisz nazwę');const colors=['#ff5a2c','#dc2f3f','#8c5cff','#21c77a','#2e9cff'];const p={id:uid('playlist'),name,description:'Twoja własna fala.',accent:colors[state.playlists.length%colors.length],custom:true,trackIds:pickerTrackId?[pickerTrackId]:[]};state.playlists.push(p);input.value='';save();renderPlaylistOptions();toast(`Utworzono ${name}`)}

function setQueue(tracks,startId){currentQueue=tracks.filter(Boolean);queueIndex=Math.max(0,currentQueue.findIndex(t=>t.id===startId));if(queueIndex<0)queueIndex=0}
async function playTrack(track,options={}){
 if(!track)return;const saved=track.temporary?saveResult(track):track;currentTrack=saved;const visible=currentView==='liked'?state.likedIds.map(getTrack).filter(Boolean):currentView==='playlist'?playlistTracks(state.playlists.find(p=>p.id===currentPlaylist)):state.tracks;if(!currentQueue.length||!currentQueue.some(t=>t.id===saved.id))setQueue(visible,saved.id);else queueIndex=currentQueue.findIndex(t=>t.id===saved.id);
 state.recentIds=[saved.id,...state.recentIds.filter(id=>id!==saved.id)].slice(0,30);save();$('#player').classList.add('show');updatePlayer();lyricsData=null;lyricsActive=-1;
 const preview=saved.preview||saved.previewUrl;if(preview&&!options.forceFull)return playPreview(saved,preview);
 if(saved.provider==='youtube'&&youtubeId(saved.url))return playYouTube(saved);
 if(saved.provider==='soundcloud'&&soundcloudUrl(saved))return playSoundCloud(saved);
 const found=await ensurePreview(saved);if(found)return playPreview(saved,found);
 playbackMode='idle';updatePlayer();openSourceDrawer();toast('Brak odtwarzalnego źródła — wybierz inne')
}
function stopAll(){const a=$('#preview-audio');a.pause();try{ytPlayer?.pauseVideo()}catch{}try{scWidget?.pause()}catch{}}
function playPreview(t,url){stopAll();const a=$('#preview-audio');a.src=url;a.volume=state.settings.volume;a.play().catch(()=>toast('Przeglądarka zablokowała odtwarzanie'));playbackMode='preview';playbackDuration=t.duration||0;updatePlayer();renderDrawer()}
function loadYouTubeApi(){if(ytReadyPromise)return ytReadyPromise;ytReadyPromise=new Promise(resolve=>{if(window.YT?.Player)return resolve();const old=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{old?.();resolve()};const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';document.head.appendChild(s)});return ytReadyPromise}
async function playYouTube(t){stopAll();playbackMode='youtube';updatePlayer();await loadYouTubeApi();const id=youtubeId(t.url);if(!ytPlayer){ytPlayer=new YT.Player('yt-player-host',{height:'1',width:'1',videoId:id,playerVars:{playsinline:1,origin:location.origin,rel:0},events:{onReady:e=>{e.target.setVolume(Math.round(state.settings.volume*100));e.target.playVideo()},onStateChange:e=>{if(e.data===YT.PlayerState.ENDED)nextTrack()},onError:()=>handlePlaybackFailure(t)}})}else{ytPlayer.loadVideoById({videoId:id,startSeconds:youtubeStart(t.url)});ytPlayer.setVolume(Math.round(state.settings.volume*100))}renderDrawer()}
function youtubeStart(url){try{const u=new URL(url),v=u.searchParams.get('t');return v?parseInt(v,10)||0:0}catch{return 0}}
async function handlePlaybackFailure(t){const p=await ensurePreview(t);if(p){toast('YouTube zablokował osadzanie — włączam podgląd');playPreview(t,p)}else{playbackMode='idle';updatePlayer();toast('Ten film nie pozwala na odtwarzanie w aplikacji')}}
function playSoundCloud(t){stopAll();const iframe=$('#sc-player-host');iframe.src=`https://w.soundcloud.com/player/?url=${encodeURIComponent(t.url)}&auto_play=true&hide_related=true&show_comments=false&show_user=true&show_reposts=false&visual=false`;playbackMode='soundcloud';setTimeout(()=>{try{scWidget=SC.Widget(iframe);scWidget.bind(SC.Widget.Events.READY,()=>{scWidget.setVolume(Math.round(state.settings.volume*100));scWidget.play();scWidget.getDuration(d=>{playbackDuration=d/1000})});scWidget.bind(SC.Widget.Events.FINISH,nextTrack)}catch{}},350);updatePlayer();renderDrawer()}
async function ensurePreview(t){if(t.preview||t.previewUrl)return t.preview||t.previewUrl;try{const results=await itunesSearch(`${t.artist} ${t.title}`);const best=results.find(x=>x.preview)||null;if(best?.preview){t.preview=t.previewUrl=best.preview;t.duration=best.duration||t.duration;if(!t.cover)t.cover=best.cover;save();return best.preview}}catch{}return''}
function togglePlayback(){if(!currentTrack)return;const a=$('#preview-audio');if(playbackMode==='preview'){a.paused?a.play():a.pause()}else if(playbackMode==='youtube'){try{ytPlayer.getPlayerState()===YT.PlayerState.PLAYING?ytPlayer.pauseVideo():ytPlayer.playVideo()}catch{}}else if(playbackMode==='soundcloud'){try{scWidget.isPaused(p=>p?scWidget.play():scWidget.pause())}catch{}}else playTrack(currentTrack)}
function nextTrack(){if(!currentQueue.length)return;if(state.settings.shuffle)queueIndex=Math.floor(Math.random()*currentQueue.length);else queueIndex++;if(queueIndex>=currentQueue.length){if(state.settings.repeat)queueIndex=0;else return}playTrack(currentQueue[queueIndex])}
function previousTrack(){if(!currentQueue.length)return;queueIndex=Math.max(0,queueIndex-1);playTrack(currentQueue[queueIndex])}
function updatePlayer(){
 if(!currentTrack)return;$('#mini-title').textContent=currentTrack.title;$('#mini-artist').textContent=currentTrack.artist;setCover($('#mini-cover'),currentTrack);setCover($('#drawer-cover'),currentTrack);$('#drawer-track-title').textContent=currentTrack.title;$('#drawer-track-artist').textContent=currentTrack.artist;const m=mediaType(currentTrack);$('#mini-badge').textContent=m.label;$('#mini-badge').className=`media-badge ${m.cls}`;$('#mini-like').textContent=state.likedIds.includes(currentTrack.id)?'♥':'♡';$('#play-pause').textContent=isPlaying()?'❚❚':'▶';$('#mini-cover .cover-play').textContent=isPlaying()?'❚❚':'▶';$('#shuffle').style.color=state.settings.shuffle?'var(--accent2)':'';$('#repeat').style.color=state.settings.repeat?'var(--accent2)':''
}
function isPlaying(){if(playbackMode==='preview')return!$('#preview-audio').paused;if(playbackMode==='youtube')try{return ytPlayer?.getPlayerState()===YT.PlayerState.PLAYING}catch{}return false}
function updateTicker(){
 let pos=0,dur=0;if(playbackMode==='preview'){const a=$('#preview-audio');pos=a.currentTime||0;dur=a.duration||playbackDuration||0}else if(playbackMode==='youtube'){try{pos=ytPlayer?.getCurrentTime()||0;dur=ytPlayer?.getDuration()||0}catch{}}else if(playbackMode==='soundcloud'&&scWidget){try{scWidget.getPosition(ms=>{playbackPosition=ms/1000});pos=playbackPosition;dur=playbackDuration}catch{}}
 playbackPosition=pos;playbackDuration=dur;const pct=dur?clamp(pos/dur*100,0,100):0;$('#current-time').textContent=formatTime(pos);$('#duration').textContent=formatTime(dur);$('#seek').value=Math.round(pct*10);$('#seek').style.setProperty('--progress',`${pct}%`);$('#player-glow').style.width=`${pct}%`;syncLyrics(pos);updatePlayer()
}
function seekTo(value){const pct=Number(value)/1000;if(playbackMode==='preview'){const a=$('#preview-audio');if(a.duration)a.currentTime=a.duration*pct}else if(playbackMode==='youtube')try{ytPlayer.seekTo((ytPlayer.getDuration()||0)*pct,true)}catch{}else if(playbackMode==='soundcloud')try{scWidget.seekTo(playbackDuration*1000*pct)}catch{}}
function applyVolume(v,persist=true){const volume=clamp(Number(v),0,1);$('#preview-audio').volume=volume;try{ytPlayer?.setVolume(Math.round(volume*100))}catch{}try{scWidget?.setVolume(Math.round(volume*100))}catch{}if(persist){state.settings.volume=volume;if(volume>0)state.settings.lastVolume=volume;save()}updateVolumeUI()}
function updateVolumeUI(){const v=Math.round((state.settings.volume??.78)*100);$('#volume').value=v;$('#volume').style.setProperty('--progress',`${v}%`);$('#volume-label').textContent=`${v}%`;$('#mute').textContent=v===0?'🔇':v<45?'🔉':'🔊'}

function openDrawer(tab='player'){if(!currentTrack)return;drawerTab=tab;$('#player-drawer').classList.add('open');$('#player-drawer').setAttribute('aria-hidden','false');renderDrawer()}
function closeDrawer(){$('#player-drawer').classList.remove('open');$('#player-drawer').setAttribute('aria-hidden','true')}
function renderDrawer(){$$('#drawer-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.drawerTab===drawerTab));if(drawerTab==='player')renderPlayerDrawer();else if(drawerTab==='lyrics')renderLyricsDrawer();else renderSourceDrawer()}
function renderPlayerDrawer(){const t=currentTrack;if(!t)return;let content='';if(playbackMode==='soundcloud')content=`<div class="player-stage"><iframe height="230" src="https://w.soundcloud.com/player/?url=${encodeURIComponent(t.url)}&auto_play=false&hide_related=true&show_comments=false&show_user=true&visual=false" allow="autoplay"></iframe></div>`;else content=`<div class="player-stage"><div class="stage-visual"><div class="stage-disc ${isPlaying()?'':'paused'}"></div><h2>${esc(t.title)}</h2><p class="muted-text">${esc(t.artist)} · ${esc(mediaType(t).label)}</p><button class="primary-button" data-toggle-play>${isPlaying()?'❚❚ Pauza':'▶ Odtwórz'}</button></div></div>`;$('#drawer-body').innerHTML=content}
async function renderLyricsDrawer(){const body=$('#drawer-body');body.innerHTML='<div class="spinner"></div>';const t=currentTrack;if(!t)return;try{lyricsData=await fetchLyrics(t);if(!lyricsData){body.innerHTML='<div class="lyrics-empty"><h3>Brak tekstu</h3><p>Nie znaleziono legalnego tekstu dla tego utworu.</p></div>';return}const lines=lyricsData.synced?parseLrc(lyricsData.synced):[];body.innerHTML=`<div class="lyrics-shell"><div class="lyrics-background"></div><div class="lyrics-head"><div class="lyrics-head-art" style="background-image:url('${esc(t.cover||'').replace(/'/g,'%27')}')"></div><div><strong>${esc(t.title)}</strong><span>${esc(t.artist)}</span></div></div>${lines.length?`<div class="lyrics-lines" id="lyrics-lines">${lines.map((l,i)=>`<div class="lyric-line" data-time="${l.time}" data-lyric-index="${i}">${esc(l.text||'♪')}</div>`).join('')}</div>`:`<div class="lyrics-lines">${String(lyricsData.plain||'').split('\n').filter(Boolean).map(x=>`<div class="lyric-line near">${esc(x)}</div>`).join('')}</div>`}<div class="lyrics-credit">Tekst: LRCLIB · wyświetlany tylko, gdy jest dostępny.</div></div>`;syncLyrics(playbackPosition,true)}catch{body.innerHTML='<div class="lyrics-empty"><h3>Nie udało się pobrać tekstu</h3><p>Sprawdź połączenie i spróbuj ponownie.</p></div>'}}
async function fetchLyrics(t){const key=`${t.artist}|${t.title}`.toLowerCase();if(lyricsCache.has(key))return lyricsCache.get(key);const params=new URLSearchParams({track_name:t.title,artist_name:t.artist});const r=await fetch(`https://lrclib.net/api/get?${params}`);if(!r.ok){lyricsCache.set(key,null);return null}const d=await r.json();const out={synced:d.syncedLyrics||'',plain:d.plainLyrics||''};lyricsCache.set(key,out);return out}
function parseLrc(text){return String(text||'').split('\n').map(line=>{const m=line.match(/^\[(\d{1,2}):(\d{2})(?:\.(\d{1,3}))?\](.*)$/);if(!m)return null;return{time:Number(m[1])*60+Number(m[2])+Number(`0.${m[3]||0}`),text:m[4].trim()}}).filter(Boolean).sort((a,b)=>a.time-b.time)}
function syncLyrics(position,force=false){if(drawerTab!=='lyrics'||!lyricsData?.synced)return;const lines=parseLrc(lyricsData.synced);let idx=-1;for(let i=0;i<lines.length;i++){if(lines[i].time<=position)idx=i;else break}if(idx===lyricsActive&&!force)return;lyricsActive=idx;$$('.lyric-line').forEach((el,i)=>{el.classList.toggle('active',i===idx);el.classList.toggle('near',Math.abs(i-idx)<=1&&i!==idx)});const active=$(`.lyric-line[data-lyric-index="${idx}"]`);active?.scrollIntoView({block:'center',behavior:force?'auto':'smooth'})}
function renderSourceDrawer(){const t=currentTrack;if(!t)return;$('#drawer-body').innerHTML=`<div class="source-grid"><p class="muted-text">Źródła są oficjalne. Fala nie pobiera muzyki i nie omija ograniczeń dostawców.</p><div class="source-provider">${['youtube','soundcloud','spotify'].map(p=>`<button class="${t.provider===p?'active':''}" style="--provider-color:${providerColor(p)}" data-source-provider="${p}">${providerLabel(p)}</button>`).join('')}</div><div class="source-input-row"><input id="source-url-input" placeholder="Wklej oficjalny link" value="${esc(t.url||'')}"><button class="primary-button" id="attach-source">Zapisz</button></div><div class="button-row"><button class="secondary-button" id="open-current-source">Otwórz źródło ↗</button><button class="secondary-button" id="find-source-web">Znajdź źródło ↗</button></div></div>`}
function openSourceDrawer(){openDrawer('source')}

function openSettings(){$('#settings-drawer').classList.add('open');$('#settings-drawer').setAttribute('aria-hidden','false');$('#google-client-id').value=state.settings.googleClientId||'';renderYoutubeAccount()}
function closeSettings(){$('#settings-drawer').classList.remove('open');$('#settings-drawer').setAttribute('aria-hidden','true')}
function initTokenClient(){const clientId=state.settings.googleClientId;if(!clientId||!window.google?.accounts?.oauth2)return false;tokenClient=google.accounts.oauth2.initTokenClient({client_id:clientId,scope:'https://www.googleapis.com/auth/youtube https://www.googleapis.com/auth/youtube.force-ssl',callback:async response=>{if(response.error)return toast(`YouTube: ${response.error}`);youtubeToken=response.access_token;await loadYoutubeProfile();renderYoutubeAccount();toast('YouTube połączony')}});return true}
function connectYoutube(){const id=$('#google-client-id')?.value.trim()||state.settings.googleClientId;if(!id)return toast('Wklej Google OAuth Client ID');state.settings.googleClientId=id;save();if(!initTokenClient())return toast('Google Identity jeszcze się ładuje — spróbuj za chwilę');tokenClient.requestAccessToken({prompt:'consent'})}
async function loadYoutubeProfile(){try{const r=await ytApi('https://www.googleapis.com/youtube/v3/channels?part=snippet&mine=true');youtubeProfile=r.items?.[0]?.snippet||null;await loadYoutubePlaylists()}catch{}}
async function ytApi(url,options={}){const r=await fetch(url,{...options,headers:{Authorization:`Bearer ${youtubeToken}`,'Content-Type':'application/json',...(options.headers||{})}});if(r.status===401){disconnectYoutube(false);throw new Error('Sesja YouTube wygasła')}if(!r.ok){const text=await r.text();throw new Error(text.slice(0,180)||'Błąd YouTube API')}return r.json()}
function disconnectYoutube(show=true){youtubeToken='';youtubeProfile=null;tokenClient=null;renderYoutubeAccount();if(show)toast('YouTube rozłączony')}
function renderYoutubeAccount(){const connected=!!youtubeToken;$('#youtube-dot').classList.toggle('connected',connected);$('#youtube-status').textContent=connected?(youtubeProfile?.title||'YouTube połączony'):'YouTube niepołączony';$('#youtube-substatus').textContent=connected?'Wyszukiwanie i playlisty aktywne':'SoundCloud działa bez konta';$('#youtube-connect-top .status-dot').classList.toggle('connected',connected);$('#youtube-connect-top b').textContent=connected?(youtubeProfile?.title||'YouTube aktywny'):'Połącz YouTube';$('#disconnect-youtube').classList.toggle('hidden',!connected);$('#youtube-account-details').classList.toggle('hidden',!connected);if(connected)$('#youtube-account-details').innerHTML=`<strong>${esc(youtubeProfile?.title||'Połączone konto')}</strong><p>Token działa tylko w tej karcie i nie jest zapisywany w bibliotece.</p>`}
async function loadYoutubePlaylists(){if(!youtubeToken)return;const data=await ytApi('https://www.googleapis.com/youtube/v3/playlists?part=snippet,contentDetails&mine=true&maxResults=50');const list=$('#youtube-playlists');if(!list)return;list.innerHTML=(data.items||[]).map(p=>`<div class="youtube-playlist-row"><div><strong>${esc(p.snippet.title)}</strong><div class="muted-text">${p.contentDetails.itemCount} filmów</div></div><button class="small-button" data-import-youtube-playlist="${esc(p.id)}">Importuj</button></div>`).join('')||'<p class="muted-text">Brak playlist na koncie.</p>'}
async function importYoutubePlaylist(id){toast('Importuję playlistę YouTube…');let pageToken='',all=[];do{const u=new URL('https://www.googleapis.com/youtube/v3/playlistItems');u.search=new URLSearchParams({part:'snippet,contentDetails',playlistId:id,maxResults:'50',...(pageToken?{pageToken}:{})});const d=await ytApi(u);all.push(...(d.items||[]));pageToken=d.nextPageToken||''}while(pageToken&&all.length<500);const title=all[0]?.snippet?.playlistTitle||'YouTube import';let p=state.playlists.find(x=>x.name===title);if(!p){p={id:uid('playlist'),name:title,description:'Zaimportowano z YouTube.',accent:'#ff4545',custom:true,trackIds:[]};state.playlists.push(p)}for(const item of all){const vid=item.contentDetails?.videoId;if(!vid)continue;let t=state.tracks.find(x=>youtubeId(x.url)===vid);if(!t){t={id:`yt-${vid}`,title:item.snippet.title,artist:item.snippet.videoOwnerChannelTitle||item.snippet.channelTitle||'YouTube',provider:'youtube',url:`https://www.youtube.com/watch?v=${vid}`,cover:item.snippet.thumbnails?.high?.url||item.snippet.thumbnails?.medium?.url||'',addedAt:Date.now(),seed:false};state.tracks.unshift(t)}if(!p.trackIds.includes(t.id))p.trackIds.push(t.id)}save();setView('playlist',p.id);closeSettings();toast(`Zaimportowano ${all.length} filmów`)}
async function saveToYoutubePlaylist(track){if(!youtubeToken)return toast('Najpierw połącz YouTube');const videoId=youtubeId(track.url);if(!videoId)return toast('To nie jest film YouTube');await loadYoutubePlaylists();openSettings();toast('Wybierz playlistę YouTube po prawej — obsługa dodawania pojawi się po wybraniu playlisty w kolejnej aktualizacji')}

function exportLibrary(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fala-music-library.json';a.click();URL.revokeObjectURL(a.href)}
function importLibrary(file){const r=new FileReader();r.onload=()=>{try{state=normalizeState(JSON.parse(r.result));save();setView('home');toast('Biblioteka zaimportowana')}catch{toast('Nieprawidłowy plik JSON')}};r.readAsText(file)}

function initParticles(){const canvas=$('#particles'),ctx=canvas.getContext('2d');let dots=[];function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;canvas.style.width=`${innerWidth}px`;canvas.style.height=`${innerHeight}px`;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const count=Math.min(95,Math.max(36,Math.floor(innerWidth/16)));dots=Array.from({length:count},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.7+.35,vx:(Math.random()-.5)*.18,vy:-(Math.random()*.26+.05),a:Math.random()*.4+.08,h:Math.random()>.68?28:350}))}function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);for(const d of dots){d.x+=d.vx;d.y+=d.vy;if(d.y<-8){d.y=innerHeight+8;d.x=Math.random()*innerWidth}if(d.x<-8)d.x=innerWidth+8;if(d.x>innerWidth+8)d.x=-8;ctx.beginPath();ctx.fillStyle=`hsla(${d.h},90%,65%,${d.a})`;ctx.shadowBlur=12;ctx.shadowColor=`hsla(${d.h},90%,60%,${d.a})`;ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw()}

function handleClick(e){
 const view=e.target.closest('[data-view]');if(view){const provider=view.dataset.provider;if(provider)activeProvider=provider;closeSettings();return setView(view.dataset.view)}
 const playlist=e.target.closest('[data-playlist]');if(playlist)return setView('playlist',playlist.dataset.playlist);
 const artist=e.target.closest('[data-artist]');if(artist)return setView('artist',artist.dataset.artist);
 const play=e.target.closest('[data-play-track]');if(play)return playTrack(getTrack(play.dataset.playTrack));
 const like=e.target.closest('[data-like-track]');if(like)return toggleLike(like.dataset.likeTrack);
 const add=e.target.closest('[data-add-track]');if(add)return openPlaylistPanel(add.dataset.addTrack,add);
 const del=e.target.closest('[data-delete-track]');if(del){const id=del.dataset.deleteTrack;state.tracks=state.tracks.filter(t=>t.id!==id);state.playlists.forEach(p=>p.trackIds=p.trackIds.filter(x=>x!==id));state.likedIds=state.likedIds.filter(x=>x!==id);save();return rerenderCurrent()}
 const preview=e.target.closest('[data-preview-result]');if(preview){const t=JSON.parse(decodeURIComponent(preview.dataset.previewResult));return playTrack(t)}
 const saveBtn=e.target.closest('[data-save-result]');if(saveBtn)return saveResult(saveBtn.dataset.saveResult);
 const saveYt=e.target.closest('[data-save-youtube-result]');if(saveYt){const t=saveResult(saveYt.dataset.saveYoutubeResult);return saveToYoutubePlaylist(t)}
 const provider=e.target.closest('[data-provider-tab]');if(provider){activeProvider=provider.dataset.provider;return renderSearch($('#provider-query')?.value||$('#global-search').value)}
 const playPl=e.target.closest('[data-play-playlist]');if(playPl){const p=state.playlists.find(x=>x.id===playPl.dataset.playPlaylist),tracks=playlistTracks(p);if(tracks.length){setQueue(tracks,tracks[0].id);playTrack(tracks[0])}return}
 if(e.target.closest('[data-play-liked]')){const tracks=state.likedIds.map(getTrack).filter(Boolean);if(tracks.length){setQueue(tracks,tracks[0].id);playTrack(tracks[0])}return}
 if(e.target.closest('[data-open-create]'))return openCreatePanel();
 const deleteP=e.target.closest('[data-delete-playlist]');if(deleteP){state.playlists=state.playlists.filter(p=>p.id!==deleteP.dataset.deletePlaylist);save();return setView('home')}
 if(e.target.closest('[data-toggle-play]'))return togglePlayback();
 const drawer=e.target.closest('[data-drawer-tab]');if(drawer){drawerTab=drawer.dataset.drawerTab;return renderDrawer()}
 const sourceProvider=e.target.closest('[data-source-provider]');if(sourceProvider){if(!currentTrack)return;currentTrack.provider=sourceProvider.dataset.sourceProvider;renderSourceDrawer();return}
 const importYt=e.target.closest('[data-import-youtube-playlist]');if(importYt)return importYoutubePlaylist(importYt.dataset.importYoutubePlaylist);
 if(e.target.closest('.panel-close'))return closeMiniPanels();
}

document.addEventListener('click',handleClick);
document.addEventListener('change',e=>{if(e.target.closest('#playlist-options'))syncPickerChoices();if(e.target.id==='import-library'&&e.target.files[0])importLibrary(e.target.files[0])});
document.addEventListener('input',e=>{if(e.target.id==='provider-query'){clearTimeout(searchTimer);searchTimer=setTimeout(()=>runSearch(e.target.value),350)}if(e.target.id==='global-search'){clearTimeout(searchTimer);searchTimer=setTimeout(()=>setView('search'),220)}});
document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();$('#global-search').focus()}if(e.key==='Escape'){closeMiniPanels();closeDrawer();closeSettings()}if(e.code==='Space'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();togglePlayback()}});
$('#run-search')?.addEventListener?.('click',()=>{});
$('#global-search').addEventListener('keydown',e=>{if(e.key==='Enter')setView('search')});
$('#add-music').addEventListener('click',()=>setView('search'));
$('#create-playlist-side').addEventListener('click',openCreatePanel);
$('#confirm-create-playlist').addEventListener('click',createPlaylist);
$('#quick-create-playlist').addEventListener('click',quickCreatePlaylist);
$('#playlist-swatches').addEventListener('click',e=>{const b=e.target.closest('[data-color]');if(!b)return;selectedPlaylistColor=b.dataset.color;$$('#playlist-swatches button').forEach(x=>x.classList.toggle('active',x===b))});
$('#play-pause').addEventListener('click',togglePlayback);$('#mini-cover').addEventListener('click',()=>currentTrack&&openDrawer('player'));$('#mini-like').addEventListener('click',()=>currentTrack&&toggleLike(currentTrack.id));$('#next').addEventListener('click',nextTrack);$('#previous').addEventListener('click',previousTrack);$('#shuffle').addEventListener('click',()=>{state.settings.shuffle=!state.settings.shuffle;save();updatePlayer()});$('#repeat').addEventListener('click',()=>{state.settings.repeat=!state.settings.repeat;save();updatePlayer()});
$('#seek').addEventListener('input',e=>seekTo(e.target.value));$('#volume').addEventListener('input',e=>applyVolume(Number(e.target.value)/100));$('#mute').addEventListener('click',()=>applyVolume(state.settings.volume>0?0:(state.settings.lastVolume||.78)));$('#lyrics-button').addEventListener('click',()=>openDrawer('lyrics'));$('#source-button').addEventListener('click',()=>openDrawer('source'));$('#expand-player').addEventListener('click',()=>openDrawer('player'));$('#close-player-drawer').addEventListener('click',closeDrawer);
$('#account-settings').addEventListener('click',openSettings);$('#youtube-connect-top').addEventListener('click',()=>youtubeToken?openSettings():openSettings());$('#close-settings').addEventListener('click',closeSettings);$('#save-and-connect').addEventListener('click',connectYoutube);$('#disconnect-youtube').addEventListener('click',()=>disconnectYoutube(true));$('#export-library').addEventListener('click',exportLibrary);
$('#drawer-body').addEventListener('click',e=>{if(e.target.closest('[data-toggle-play]'))togglePlayback();if(e.target.id==='attach-source'&&currentTrack){const url=$('#source-url-input').value.trim();if(!validUrl(url))return toast('Wklej prawidłowy link');currentTrack.url=url;currentTrack.provider=url.includes('soundcloud.com')?'soundcloud':url.includes('youtube.com')||url.includes('youtu.be')?'youtube':url.includes('spotify.com')?'spotify':currentTrack.provider;save();toast('Źródło zapisane');renderSourceDrawer()}if(e.target.id==='open-current-source'&&currentTrack?.url)window.open(currentTrack.url,'_blank','noopener');if(e.target.id==='find-source-web'&&currentTrack){const q=encodeURIComponent(`${currentTrack.artist} ${currentTrack.title}`);window.open(`https://www.youtube.com/results?search_query=${q}`,'_blank','noopener')}const line=e.target.closest('[data-time]');if(line)seekAbsolute(Number(line.dataset.time))});
function seekAbsolute(sec){if(playbackMode==='preview')$('#preview-audio').currentTime=sec;else if(playbackMode==='youtube')try{ytPlayer.seekTo(sec,true)}catch{}else if(playbackMode==='soundcloud')try{scWidget.seekTo(sec*1000)}catch{}}
$('#preview-audio').addEventListener('play',updatePlayer);$('#preview-audio').addEventListener('pause',updatePlayer);$('#preview-audio').addEventListener('ended',nextTrack);$('#preview-audio').addEventListener('loadedmetadata',()=>{playbackDuration=$('#preview-audio').duration||0});

ticker=setInterval(updateTicker,250);applyVolume(state.settings.volume,false);renderSidebar();updateCounts();renderYoutubeAccount();setView('home');initParticles();setTimeout(()=>initTokenClient(),1100);
